let nameMap = {
  "shanks": "http://codebuild.me/",
  "小锅": "http://www.jianshu.com/users/3b40e55ec6d5/latest_articles",
  "lfb_CD": "http://weibo.com/lfbWb",
  "mmoaay": "http://mmoaay.photo/",
  "Yake": "http://blog.csdn.net/yake_099",
  "小铁匠Linus": "http://weibo.com/linusling",
  "SergioChan": "https://github.com/SergioChan",
  "天才175": "http://weibo.com/u/2916092907",
  "靛青K": "http://www.dianqk.org/",
  "numbbbbb": "http://numbbbbb.com/",
  "千叶知风": "http://weibo.com/xiaoxxiao",
  "CMB": "https://github.com/chenmingbiao",
  "saitjr": "http://www.brighttj.com",
  "Prayer": "http://www.futantan.com",
  "pmst": "http://www.jianshu.com/users/596f2ba91ce9/latest_articles",
  "ray16897188": "http://www.jianshu.com/users/97c49dfd1f9f/latest_articles",
  "BridgeQ": "http://wxgbridgeq.github.io/",
  "小袋子": "http://daizi.me",
  "我偏笑": "http://blog.csdn.net/nsnirvana",
  "riven": "http://weibo.com/riven0951",
  "Cee": "https://github.com/Cee",
  "星夜暮晨": "http://www.jianshu.com/users/ef1058d2d851",
  "JackAlan": "http://ijack.pw/",
  "walkingway": "http://chengway.in/",
  "&nbsp": "https://github.com/initiOSJava",
  "bestswifter": "http://bestswifter.com",
  "CoderAFI": "http://coderafi.github.io/",
  "aaaron7": "http://www.jianshu.com/users/9efd08855d3a/",
  "zltunes": "http://zltunes.com"
}

export default nameMap
